version: '3'
services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE creates a database (optional)
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # MUST use MYSQL_USER & MYSQL_PASSWORD together; together
      # they grant user permissions on MYSQL_DATABASE
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_HOST_DATA_DIR}:${MYSQL_GUEST_DATA_DIR}
  server:
    container_name: server
    build:
      context: ./server
      args:
        HOSTNAME: $HOSTNAME
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - mysql
    volumes:
      - ${TAO_HOST_DIR}:${TAO_GUEST_DIR}
