version: '3'
services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_HOST_DATA_DIR}:${MYSQL_GUEST_DATA_DIR}
  server:
    container_name: server
    build:
      context: ./server
      args:
        HOSTNAME: $HOSTNAME
        SSL_ORGANIZATION_NAME: $SSL_ORGANIZATION_NAME
        SSL_ORGANIZATIONAL_UNIT_NAME: $SSL_ORGANIZATIONAL_UNIT_NAME
        SSL_EMAIL_ADDRESS: $SSL_EMAIL_ADDRESS
        SSL_LOCALITY_NAME: $SSL_LOCALITY_NAME
        SSL_STATE: $SSL_STATE
        SSL_COUNTRY_NAME: $SSL_COUNTRY_NAME
        SSL_COMMON_NAME: $SSL_COMMON_NAME
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${SSH_PORT}:22"      
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    volumes:
      - ${TAO_HOST_DIR}:${TAO_GUEST_DIR}
